# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [1]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch


# Create random tensor
tensor_A = torch.rand(7, 7)
tensor_A


tensor([[0.1187, 0.4598, 0.3834, 0.0657, 0.4567, 0.0256, 0.8257],
        [0.3592, 0.2909, 0.3519, 0.9846, 0.4756, 0.3614, 0.8577],
        [0.4357, 0.3222, 0.3576, 0.7917, 0.7070, 0.1354, 0.7439],
        [0.1378, 0.6053, 0.5019, 0.3486, 0.3960, 0.0256, 0.2108],
        [0.3655, 0.9864, 0.4543, 0.6851, 0.1591, 0.2545, 0.1163],
        [0.0605, 0.2498, 0.5170, 0.8619, 0.7458, 0.9280, 0.7656],
        [0.8783, 0.7924, 0.1033, 0.2276, 0.1317, 0.7678, 0.5695]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [3]:
# Create another random tensor
tensor_B = torch.rand(1, 7)
tensor_B
# Perform matrix multiplication
tensor_multiplication = tensor_A.mm(tensor_B.transpose(0,1))
tensor_multiplication


tensor([[1.1682],
        [2.1272],
        [2.1412],
        [1.4015],
        [1.8628],
        [2.2399],
        [1.5149]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [4]:
# Set manual seed
torch.manual_seed(0)

# Create two random tensors
rand_tensor_A = torch.rand(7, 7)
rand_tensor_B = torch.rand(1, 7)

# Matrix multiply tensors
tensor_multiplication = rand_tensor_A.mm(rand_tensor_B.transpose(0,1))
tensor_multiplication


tensor([[1.8542],
        [1.9611],
        [2.2884],
        [3.0481],
        [1.7067],
        [2.5290],
        [1.7989]])

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [5]:
# Set random seed on the GPU
torch.cuda.manual_seed(1234)



### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [6]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"
device

# Create two random tensors on GPU
tensor_A = torch.rand(2, 3).to(device='cuda')
tensor_B = torch.rand(2, 3).to(device='cuda')
tensor_A, tensor_B



(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [12]:
# Perform matmul on tensor_A and tensor_B
multiplied = torch.mm(tensor_A, tensor_B.transpose(0,1))
multiplied

tensor([[0.3647, 0.4709],
        [0.5184, 0.5617]], device='cuda:0')

### 8. Find the maximum and minimum values of the output of 7.

In [14]:
# Find max
multiplied.max()

# Find min
multiplied.min()

tensor(0.3647, device='cuda:0')

### 9. Find the maximum and minimum index values of the output of 7.

In [17]:
# Find arg max
multiplied.argmax()

# Find arg min
multiplied.argmin()


tensor(0, device='cuda:0')


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [32]:
# Set seed
torch.manual_seed(7)

# Create random tensor
tensor_1 = torch.rand(1, 1, 1, 10)

# Remove single dimensions
squeezed_tensor_1 = tensor_1.squeeze((0, 1, 2))

# Print out tensors and their shapes
squeezed_tensor_1, squeezed_tensor_1.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]),
 torch.Size([10]))